Renovate:
  image:
    name: ghcr.io/renovatebot/renovate:41

  variables:
    LOG_LEVEL: 'debug'
    RENOVATE_BASE_DIR: $CI_PROJECT_DIR/renovate
    RENOVATE_ENDPOINT: $CI_API_V4_URL
    RENOVATE_PLATFORM: gitlab
    RENOVATE_REPOSITORY_CACHE: 'disabled'
    RENOVATE_AUTODISCOVER_FILTER: '/renovate-repro/'
    RENOVATE_EXTRA_FLAGS: --autodiscover=true --autodiscover-filter='/renovate/'

  script:
    - renovate $RENOVATE_EXTRA_FLAGS
  rules:
    - if: '$CI_PIPELINE_SOURCE == "push"'
