on:
  push:

jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Self-hosted Renovate
        uses: renovatebot/github-action@v43.0.2
        env:
          LOG_LEVEL: 'debug'
        with:
          configurationFile: .github/renovate-global.js
          token: ${{ secrets.GITHUB_TOKEN }}
